#!/uns/bin/zsh -
COLS=`awk <$1 '{print NF; exit}'`
echo -n "\\\\begin{tabular}{|l|"
for i in {1..$[COLS-1]}; do echo -n "r|"; done
echo "}\\\\hline"
sed -e 's/	\+/ \& /g' -e 's/\( \& *\)\?$/\\\\\\hline/' $1
echo "\\\\end{tabular}"
