#!/uns/bin/perl
BEGIN {
# FIX: These table headings need to be kept
# in synch w/ macros-make-subset-metacateg-from-mac script
# (which uses em_constants' @mcat_XXXX lists)
print '
%\usepackage{graphics}
%\newcommand{\black}{\ensuremath{\blacksquare}}
\newcommand{\black}{\vrule height5.5pt depth0.5pt width6pt}
{\small
\addtolength{\columnsep}{-.5\columnsep}
% The *{n}{c|} below creates n duplicate columns of that type (centered, here)
\begin{tabular}{|r|*{10}{c|}}\hline
\rotatebox{90}{\parbox{1in}{Percentage of~ \\\\ macro names}~} &
\rotatebox{90}{Null define~} &
\rotatebox{90}{Constant~} &
\rotatebox{90}{Expression~} &
\rotatebox{90}{Statement~} &
\rotatebox{90}{Type related~} &
\rotatebox{90}{Syntactic~} &
\rotatebox{90}{Symbols~} &
\rotatebox{90}{Unknown symbol~} &
\rotatebox{90}{Not C code~} &
\rotatebox{90}{Failed classification~}
\\\\ \hline
';
}

END {
print '
\end{tabular}}
';
}

if (defined $ARGV[0]) {
  $sum = $ARGV[0];
  shift;
  $pct = 1;
} else {
  $pct = 0;
}

while (<>) {
  ($count,$marks) = /^( +\d+)\s(.*)$/;

  # print STDERR "$count <<$marks>>\n";
  @m = split(//,$marks);
  $out = join("&", @m);
  $out =~ s/\*/\\black/g;

  if (100*$count/$sum >= 0.05) {
    if ($pct == 0) {
      print "$count &";
    } else {
      # Should use two_significant_digits from em_util.pm
      my $pct_string = sprintf "%6.02g\\% &", 100*$count/$sum;
      # If only one significant digit, fix.
      $pct_string =~ s/^(\s*)  (\d)(\\%)/$1$2.0$3/;
      $pct_string =~ s/^(\s*) (0\.0*\d)(\\%)/$1${2}0$3/;
      print $pct_string;
    }
    print $out, ' \\\\ \\hline', "\n";
  }
}
