#!/uns/bin/perl
BEGIN {
# FIX: These table headings need to be kept
# in synch w/ macros-make-subset-categorizations-from-mac script
print '
%\usepackage{graphics}
%\newcommand{\black}{\ensuremath{\blacksquare}}
\newcommand{\black}{\vrule height5.5pt depth0.5pt width6pt}
{\small
\addtolength{\columnsep}{-.5\columnsep}
\begin{tabular}{|r|*{22}{c|}}\hline
\rotatebox{90}{Percentage of macro names} &
\rotatebox{90}{failed categorization} &
\rotatebox{90}{null define} &
\rotatebox{90}{expression} &
\rotatebox{90}{expression with assignment} &
\rotatebox{90}{expression with free variables~} &
\rotatebox{90}{literal} &
\rotatebox{90}{constant} &
\rotatebox{90}{some constant} &
\rotatebox{90}{has type argument} &
\rotatebox{90}{uses macro as function} &
\rotatebox{90}{uses macro as type} &
\rotatebox{90}{uses type argument} &
\rotatebox{90}{expands to type} &
\rotatebox{90}{expands to reserved word} &
\rotatebox{90}{statement} &
\rotatebox{90}{recursive} &
\rotatebox{90}{assembly code} &
\rotatebox{90}{expands to syntax tokens} &
\rotatebox{90}{mismatched entities} &
\rotatebox{90}{token pasting} &
\rotatebox{90}{stringization}
\\\\\\hline
';
}

END {
print '
\end{tabular}}
';
}

if (defined $ARGV[0]) {
  $sum = $ARGV[0];
  shift;
  $pct = 1;
} else {
  $pct = 0;
}

while (<>) {
  ($count,$marks) = /^( +\d+)\s(.*)$/;

#  print STDERR $count, "\n";
  @m = split(//,$marks);
  $out = join("&", @m);
  $out =~ s/\*/\\black/g;

  if (100*$count/$sum >= 0.05) {
    if ($pct == 0) {
      print "$count &";
    } else {
      printf "%6.02g\\% &",100*$count/$sum;
    }
    print $out, ' \\\\\\hline', "\n";
  }
}
