#!/uns/bin/zsh -
# -*- zsh -*-
if [[ "$1"x != ""x ]]; then
  INPUT="$1"
else
  INPUT=""
fi
OUT="/tmp/latexify.$$"
cat $INPUT >$OUT
COLS=`awk <$OUT '{print NF; exit}'`
echo -n "\\\\begin{tabular}{|l|"
for i in {1..$[COLS-1]}; do echo -n "r|"; done
echo "} \\\\hline"
sed -e 's/	\+/ \& /g' -e 's/\( \& *\)\?$/ \\\\ \\hline/' $OUT
echo "\\\\end{tabular}"
rm -f $OUT
