#!/uns/bin/perl -w
BEGIN {
my $cdefined = `sum-column 1 <tbl-subset-categories`;
chomp($cdefined);
# FIX: These table headings need to be kept
# in synch w/ macros-make-subset-metacateg-from-mac script
# (which uses em_constants' @mcat_XXXX lists)
print '
%\usepackage{graphics}
%\newcommand{\black}{\ensuremath{\blacksquare}}
\newcommand{\black}{\vrule height5.5pt depth0.5pt width6pt}
{\small
\addtolength{\tabcolsep}{-.6\tabcolsep}
% The *{n}{c|} below creates n duplicate columns of that type (centered, here)
\begin{tabular}{|r|*{10}{c|}ll}\cline{1-11}
% The struts ensure that all the columns are equally wide.
\newlength{\headht}\settowidth{\headht}{Percentage of ' . $cdefined . '~}
\rotatebox{90}{\parbox{\headht}{Percentage of ' . $cdefined . '~ \\\\ multiply-defined~ \\\\ macro names\\strut~}} &
\rotatebox{90}{Null define~\\strut} &
\rotatebox{90}{Constant~\\strut} &
\rotatebox{90}{Expression~\\strut} &
\rotatebox{90}{Statement~\\strut} &
\rotatebox{90}{Type related~\\strut} &
\rotatebox{90}{Syntactic~\\strut} &
\rotatebox{90}{Symbols~\\strut} &
\rotatebox{90}{Unknown symbol~\\strut} &
\rotatebox{90}{Not C code~\\strut} &
\rotatebox{90}{Failed classification~\\strut}
\\\\ \cline{1-11}
';
}

END {
print '
\end{tabular}}
';
}

if (defined $ARGV[0]) {
  $sum = $ARGV[0];
  shift;
  $pct = 1;
} else {
  $pct = 0;
}

while (<>) {
  ($count,$marks) = /^( +\d+)\s(.*)$/;

  # print STDERR "$count <<$marks>>\n";
  # Omit lines for less than one-twentieth of a percent
  if (100*$count/$sum >= 0.05) {
    $marks =~ s/\^.*$//;
    @m = split(//,$marks);
    $out = join("&", @m);
    $out =~ s/\*/\\black/g;
    $out =~ s/\</\$\\Leftarrow\$/g;

    if ($pct == 0) {
      print "$count &";
    } else {
      # Should use two_significant_digits from em_util.pm
      my $pct_string = sprintf "%6.02g\\%% &", 100*$count/$sum;
      # If only one significant digit, fix.
      $pct_string =~ s/^(\s*)  (\d)(\\%)/$1$2.0$3/;
      $pct_string =~ s/^(\s*) (0\.0*\d)(\\%)/$1${2}0$3/;
      print $pct_string;
    }
    print $out, ' \\\\ \\cline{1-11}', "\n";
  }
}
