#!/uns/bin/zsh -
# -*-zsh-*-
# macros-make-data

if [[ $# != 1 ]]; then
  echo "Usage: $0 <state-files-directory>"
  exit -1
fi

TM=$PWD
STATEFILESDIR=$1
cd $STATEFILESDIR

for i in *.state(.); do
  echo $i
  em_reports -s $i -t -d $TM:${i%%.*}
done
