#!/uns/bin/zsh -
# run on *.mac files
for i in "$@"; do
  SUM=`awk < $i '$0 !~ /^[%#]/ && $NF ~ /FromStdin/ { print $2 }' | sort -n | uniq -c | tee /tmp/$i.$$ | awk '{sum += ($1 * $2)} END {print sum}'`
  (echo "$SUM"; awk < /tmp/$i.$$ '{total += $1*$2; printf "%d %d\n", $2, total}') | macros-make-buckets-and-percentages ${i%%.mac} > ${i%%.mac}.freqdef
#'$2 >= 10 && $2 > last + 1 { for (last++; last < 10; last++) {printf "%d %2.2f\n",last, 100*tot/'$SUM';} } $2 >= 10 {print "10 100.00"; exit } $2 > last+1 { for (last++; last < $2; last++) { printf "%d %2.2f\n",last,100*tot/'$SUM'; } } {tot += $1*$2; printf "%d %2.2f\n", $2, 100*tot/'$SUM'; last = $2}' >> ${i%%.mac}.freqdef
  rm -f /tmp/$i.$$
done
