#!/uns/bin/zsh
awk '/^#LINESNI#/ \
{ nextln = 1; next} nextln==1 {phys = $1; ncnb = $2; sumphys+= phys; sumncnb += ncnb; nextln = 0; \
gsub(/\..*$/, "", FILENAME); \
print FILENAME " " phys " " ncnb; next} END { print "Total " sumphys " " sumncnb } ' "$@"
