#!/uns/bin/zsh
# use macros-make-categories-tbl-from-stat *.stat
# FIX: use getopts 

# The .awk file needs to be in the same directory
# as this script -- ${0:h} is the same as `dirname $0`
SCRIPT_DIR=${0:h}

if [[ $1 == "-h" ]]; then
    echo "Usage: $0 [-t] [-p] <stat-files>"
    echo " -t means don't output for latex, use tab-delimiters"
    echo " -p means give numbers as percentages"
    exit 0;
fi

while getopts "pt" OPT; do
    if [[ $OPT == "p" ]]; then
	OPTS=($OPTS -v usepct=1)
    fi
    if [[ $OPT == "t" ]]; then
	OPTS=($OPTS -v nolatex=1)
    fi
done
shift $[$OPTIND-1]

gawk $OPTS -f $SCRIPT_DIR/macros-make-categories-tbl-from-stat.awk "$@"
