#!/uns/bin/zsh

# Don't use this; it's inlined in the Makefile.

macros-make-use-frequency-tbl-from-mac "$@"
# rm -f freq_of_use-tbl.txt
# xargs -n12 means only do 12 columns at a time, so that we get 
# multiple smaller tables
# Use ${0:h} (like `dirname $0`) to get at the left-edge headings
# This means the frequse.buckets file must be in the same directory
# as the script that gets executed (not necessarily where the script
# lives, maybe where a symlink to the script lives)
echo *.frequse | xargs -n12 paste ${0:h}/frequse.buckets
