#!/uns/bin/zsh
echo "Package	code	code, macro	macro	code, cond	code, macro, cond	macro, cond	cond	no uses"
# Input to awk is a file with 8 lines, each representing one of the
# 8 categorizations, alphabetized:
#    Code CodeCond CodeMacro CodeMacroCond Cond Macro MacroCond NoUses
# But I want to output in the order
#    Code CodeMacro Macro CodeCond CodeMacroCond MacroCond Cond NoUses
# for i in "$@"; ( echo $i; macros-how-used-ni-from-mac $i ) | awk 'END { print substr(file, 1, length(file)-4) "	" c1 "	" c2 "	" c3 "	" c4 } NR == 1 {file = $0} NR == 2 {c1 = $1} NR == 3 { c2 = $1 } NR == 4 {c3 = $1} NR == 5 {c4 = $1}' | sed 's/1\?\.mac / /' | awk 'NF == 5'

for i in "$@"; ( echo $i; macros-how-used-ni-from-mac $i ) | awk 'END { print substr(file, 1, length(file)-4) "	" c1 "	" c3 "	" c6 "	" c2 "	" c4 "	" c7 "	" c5 "	" c8 } NR == 1 {file = $0} NR == 2 {c1 = $1} NR == 3 { c2 = $1 } NR == 4 {c3 = $1} NR == 5 {c4 = $1} NR == 6 {c5 = $1} NR == 7 {c6 = $1} NR == 8 {c7 = $1} NR == 9 {c8 = $1}' | awk 'NF == 9'
