#!/uns/bin/zsh -f
# macros-make-data
EXTRA_OPTS=(-g 14)
if [[ $# != 1 ]]; then
  echo "Usage: $0 <packages-directory>"
  exit -1
fi

TM=$PWD
PKG=$1
cd $PKG

for i in *(/); do 
  echo $i
  pushd $i
    NM=${i%%-*}
    ( cat c-files-listing || find-c ) \
     | em_analyze -i -t $EXTRA_OPTS -d $TM:$NM > $TM/$NM.out 2> $TM/$NM.err || \
         (cd ..; echo $i >> failures)
  popd
done
