#!/uns/bin/zsh -f
COL=$1; shift
files=($@)
cmd=("<(title-weight-sorted-column -c $COL "${^files}")")
print -u2 $cmd
eval paste $cmd
#c=1
#for i in $files; do
#    title-weight-sorted-column -c $COL $i > out.$c
#    let c++
#done
#
#paste out.{1..$c}
#rm -f out.{1..$c}


