#!/uns/bin/perl -w

sub sum_through {
  my $i = $_[0];
  for (; $i >= 0; $i--) {
    if (defined($cum[$i])) { return $cum[$i]; }
  }
  return 0;
}

$file = shift @ARGV;

chop($total = <>);
exit if ((!$total) || ($total == 0));

while (<>) {
  @F = split(' ');
  $cum[$F[0]] = $F[1];
}

@buckets = (0,1,2,3,4,5,6,8,10,20,40,80);

print "$file\n";
foreach $i (@buckets) {
#  printf "%2d %2.2f\n", $i, 100*sum_through($i)/$total;
  printf "%2.2f\n", 100*sum_through($i)/$total;
}

# printf "%2.2f\n", 100;
