#!/uns/bin/perl -w

# Take a raw-directives-hist, which is a list of lines of the form
#  NCNB_lines package define elif else endif error ident if ifdef ifndef import include include_next line pragma undef

# Output a baked-directives-hist, which is a list of lines of the form
#  package define undef include conditional line other
# Also output a total line.

# The output is correctly in reverse order, since Excel reverses the lines
# (and columns!)

$tot_lines = 0;
$tot_def = 0;
$tot_undef = 0;
$tot_include = 0;
$tot_cond = 0;
$tot_line = 0;
$tot_other = 0;
$tot_total = 0;

$file = shift @ARGV;
open(FILE, $file);
while (<FILE>)
{
  my ($ncnb_lines, $package, $define, $elif, $else, $endif, $error, $ident, $if, $ifdef, $ifndef, $import, $include, $include_next, $line, $pragma, $undef) = split;

  # $package
  # $ncnb_lines
  # $define
  # $undef
  $ncnb_lines /= 100;
  my $this_include = $import + $include + $include_next;
  my $this_cond = $if + $ifdef + $ifndef + $elif + $else + $endif;
  # $line
  my $this_other = $error + $ident + $pragma;
  my $this_total = $define + $undef + $this_include + $this_cond + $line + $this_other;

  push(@lines, [$package, $this_other/$ncnb_lines, $line/$ncnb_lines, $this_cond/$ncnb_lines, $this_include/$ncnb_lines, $undef/$ncnb_lines, $define/$ncnb_lines, $this_total/$ncnb_lines]);

  $tot_lines += $ncnb_lines;
  $tot_def += $define;
  $tot_undef += $undef;
  $tot_include += $this_include;
  $tot_cond += $this_cond;
  $tot_line += $line;
  $tot_other += $this_other;
  $tot_total += $this_total;
}
close(FILE);

# Sort by total
@lines_sorted = sort { $$a[7] <=> $$b[7] } @lines;

print join("\t", "package", "other", "line", "conditional", "include", "undef", "define", "total"), "\n";
print "Average";
foreach $val ($tot_other/$tot_lines, $tot_line/$tot_lines, $tot_cond/$tot_lines, $tot_include/$tot_lines, $tot_undef/$tot_lines, $tot_def/$tot_lines, $tot_total/$tot_lines)
{ printf("\t%2.3f", $val); }
print "\n";
foreach $line_ref (@lines_sorted)
{ print shift(@$line_ref);
  foreach $val (@$line_ref)
    { printf("\t%2.3f", $val); }
  print "\n";
  # "$package\t$this_other\t$line\t$this_cond\t$this_include\t$undef\t$define\n";
}
