#!/uns/bin/zsh -
# Should only take one argument, a .mac file.
# Eighth field is something like "CodeCond" or "NoUses".
# Cool (lame) hack to add one of each categories via the echo,
# then decrement the counted (uniq's output) sum using the awk at 
# the end of the pipeline
(echo "Code\nCodeCond\nCodeMacro\nCodeMacroCond\nCond\nMacro\nMacroCond\nNoUses"; awk < "$1" 'NR>1 && $0 !~ /^[%#]/ && $10 !~ /^FromInclude/ {print $8}') | sort | uniq -c | awk '$1--'
