#!/uns/bin/perl -w
#!/uns/bin/perl -w
BEGIN { 
  use Getopt::Std;
  $opt_c = 1;
  $getopts_option_letters = 'c:';
# FIX: why doesn't the below work?
#  use vars map { '$opt_' . $_ if ($_ ne ':' && $_ ne '')} split (/:?/,$getopts_option_letters);
  use vars qw($opt_c);
}
getopts($getopts_option_letters);
my ($title,$weight) = split(/\s+/,<>);
print "$title\n$weight\n--\n";
while (<>) {
  next if /^\#/; # skip # lines
  push @values, (split("\t",$_))[$opt_c-1]; # access col $opt_c, starting w/ 1
}
print join("\n",sort { $b <=> $a } @values), "\n";
