#!/uns/bin/perl -n
# $Id$
# all-directive-lines

# Print out all # preprocessor directive lines
# being sure to include spliced lines (i.e. those ending in \)
# FIX: do strings get automatically included in macro defs
# FIX: this doesn't handle the wierd behaviour when there is
# an unclosed comment

if ( /^\#/ || $still == 1) { 
  print;
  if (/\\$/) { 
    $still = 1;
  } else {
    $still = 0;
  } 
};

