/*
 * This file was generated automatically by xsubpp version 1.9504 from the 
 * contents of backcalls.xs. Do not edit this file, edit backcalls.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "backcalls.xs"
/* $Id$
 * By Greg J. Badros, Aug. 27 1997
 * 
 * These are simple functions to expose some C data structures
 * to the perl callbacks called from pcpp
 *
 * FIXGJB: Need the below information available:	
   is_system_include_file()
   system_include_depth()
 */


#ifdef __cplusplus
extern "C" {
#endif
#define bool int
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "pcpp.h"
#include "cpplib.h"
#include "cpphash.h"
#include "bison-stack.h"
// #include "globals.h"
#include "tree_stk.h"
#include "nmetab.h"
#include "lexer.h"

#ifdef __cplusplus
}
#endif

extern TreeStack *ParseStack;

XS(XS_pcp3_SzToken)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: pcp3::SzToken(i)");
    {
	int	i = (int)SvIV(ST(0));
	char *	RETVAL;
#line 46 "backcalls.xs"
	RETVAL = SzFromToken((enum cpp_token_id) i);
#line 55 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_SumCchExpansionOffset)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::SumCchExpansionOffset()");
    SP -= items;
    {
	cpp_buffer * buffer = parse_in.buffer;
	long sum = 0;
	int cbuffersBack = 0;
#line 70 "backcalls.xs"
	while (buffer != CPP_NULL_BUFFER(&parse_in)) {
	    if (buffer->nominal_fname) {
		break;
	    } else {
		/* do not count the leading "@ " */
		long cch = buffer->cur - buffer->buf - 2;
		sum += cch;
		cbuffersBack++;
		buffer = CPP_PREV_BUFFER(buffer);
	    }
	}
	XPUSHs(sv_2mortal(newSViv(sum)));
	XPUSHs(sv_2mortal(newSViv(cbuffersBack)));
#line 86 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_CbuffersBack)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::CbuffersBack()");
    {
	int	RETVAL;
#line 92 "backcalls.xs"
	RETVAL=CbuffersDeep(&parse_in);
#line 101 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_MacroExpansionHistory)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::MacroExpansionHistory()");
    SP -= items;
    {
	cpp_buffer * buffer = parse_in.buffer;
	int cbuffersBack = 0;
#line 113 "backcalls.xs"
	while (buffer != CPP_NULL_BUFFER(&parse_in)) {
	    if (buffer->data == 0) {
		break;
	    } else {
		HASHNODE *macro = buffer->data;
		if (macro) {
		    int offset = buffer->cur - buffer->buf;
		    int cargs_or_negative = -1;
		    int from_what = 0;
		    if (macro->type == T_MACRO || macro->type == T_DISABLED)
			cargs_or_negative = macro->value.defn->nargs;
		    from_what = 1 + IargWithOffset(offset,
						   cargs_or_negative,
						   buffer->args);
		    XPUSHs(sv_2mortal(newSVpvf("%s#%d[%d]",macro->name,from_what,
					       offset)));
		} else
		    XPUSHs(sv_2mortal(newSVpv("",0)));
		cbuffersBack++;
		buffer = CPP_PREV_BUFFER(buffer);
	    }
	}
#line 140 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_ArgOf)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::ArgOf()");
    {
	HASHNODE * macro = (HASHNODE*)(parse_in.buffer->data);
	int offset = parse_in.buffer->cur - parse_in.buffer->buf - 1;
	struct argdata * args = parse_in.buffer->args;
	int	RETVAL;
#line 145 "backcalls.xs"
	RETVAL = -2; /* FIXNOWGJB */
	if (args)
	  RETVAL = IargWithOffset(offset, 
				  macro->type==T_MACRO?macro->value.defn->nargs:
				  -macro->type, args) + 1;
#line 162 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_CchOffset)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::CchOffset()");
    {
	cpp_buffer * buffer = parse_in.buffer;
	int cbuffersBack = 0;
	int	RETVAL;
#line 162 "backcalls.xs"
	RETVAL=0;
	if (buffer->cur == 0 || buffer->buf == 0)
     	  goto done;
	while (buffer != CPP_NULL_BUFFER(&parse_in)) {
	    if (buffer->nominal_fname) {
		break;
	    } else {
		cbuffersBack++;
		buffer = CPP_PREV_BUFFER(buffer);
	    }
	}
	RETVAL=buffer->cur - buffer->buf;
	done:
#line 192 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_InFname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::InFname()");
    {
	char *	RETVAL;
#line 195 "backcalls.xs"
	RETVAL = options.in_fname;
#line 208 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_Fname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::Fname()");
    {
	cpp_buffer * buffer = cpp_file_buffer(&parse_in);
	char *	RETVAL;
#line 207 "backcalls.xs"
	if (buffer && buffer->nominal_fname) {
	    RETVAL = buffer->nominal_fname;
	} else {
	    RETVAL = "@NONE@";
	}
#line 229 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_FnameNominal)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::FnameNominal()");
    {
	char *	RETVAL;
#line 223 "backcalls.xs"
	if (parse_in.buffer)
	  RETVAL = parse_in.buffer->nominal_fname;
	else
	  RETVAL = "@NOFILE@";
#line 248 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_ExpansionLookup)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: pcp3::ExpansionLookup(sz)");
    {
	char *	sz = (char *)SvPV(ST(0),na);
	char *	RETVAL;
#line 239 "backcalls.xs"
	HASHNODE *hp = cpp_lookup(&parse_in,sz,-1,-1);
	RETVAL = "@NOTFOUND@";
	if (hp)
          RETVAL = hp->value.defn->expansion;
#line 268 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_CchOutput)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::CchOutput()");
    {
	int	RETVAL;
#line 253 "backcalls.xs"
	RETVAL = cBytesOutput;
#line 284 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_CchCppRead)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::CchCppRead()");
    {
	int	RETVAL;
#line 263 "backcalls.xs"
	RETVAL = cBytesCppRead;
#line 300 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_FExpandingMacros)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::FExpandingMacros()");
    {
	int	RETVAL;
#line 274 "backcalls.xs"
	RETVAL = !parse_in.no_macro_expand;
#line 316 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_ParseStateStack)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::ParseStateStack()");
    SP -= items;
    {
#line 285 "backcalls.xs"
	extern short *yyss;
	extern short *yyssp;
#line 333 "backcalls.c"
#line 288 "backcalls.xs"
	short *ssp1 = yyss - 1;
	if (!fShouldParse) {
	    XPUSHs(sv_2mortal(newSVpv("@NOT_PARSING@",0)));
	}
	while (ssp1+1 != NULL && ssp1 != yyssp)
	    XPUSHs(sv_2mortal(newSViv(*++ssp1)));
#line 341 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_SetParseStateStack)
{
    dXSARGS;
    SP -= items;
    {
#line 302 "backcalls.xs"
	extern short *yyss;
	extern short *yyssp;
	extern yysstype_p yyvsp;
#line 356 "backcalls.c"
#line 306 "backcalls.xs"
	int i = 0;
	if (!fShouldParse) return;
        /* Reset stack to empty */
        yyssp = yyss-1;
	while (i < items) {
	    short val = (int)SvIV(ST(i));
            *++yyssp = val;
            *++yyvsp = NULL;
	    i++;
	}
#line 368 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_PushBuffer)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: pcp3::PushBuffer($buffer_to_push, $s_start)");
    SP -= items;
    {
#line 327 "backcalls.xs"
	int length = 0;
	int len = 0;
 	char *szBuf = SvPV(ST(0),length);
	cpp_buffer *pbuf;
	int ichStart = SvIV(ST(1));
	if ((len = strlen(szBuf)) != length) {
	    warn("PushBuffer cannot handle strings with embedded NULLs\n");
	}

	pbuf = cpp_push_buffer(&parse_in,szBuf,length,1 /* FROM PERL */);
	pbuf->ichSourceStart = ichStart - 1;
	pbuf->ichSourceEnd = ichStart + length;
        pbuf->nominal_fname = "FromPerl";
#line 395 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_EnterScope)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::EnterScope()");
    SP -= items;
    {
#line 349 "backcalls.xs"
	if (!fShouldParse) goto done;
	enter_scope(ParseStack->contxt);
	done:
#line 412 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_ExitScope)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::ExitScope()");
    SP -= items;
    {
#line 361 "backcalls.xs"
	if (!fShouldParse) goto done;
	exit_scope(ParseStack->contxt);
	done:
#line 429 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_PushHashTab)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::PushHashTab()");
    SP -= items;
    {
#line 371 "backcalls.xs"
	cpp_push_hashtab(&parse_in);
#line 444 "backcalls.c"
	PUTBACK;
	return;
    }
}

XS(XS_pcp3_PopHashTab)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::PopHashTab()");
    {
#line 379 "backcalls.xs"
	cpp_pop_hashtab(&parse_in);
#line 458 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_SetParseDebugging)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::SetParseDebugging()");
    {
#line 388 "backcalls.xs"
 	ct_yydebug = 1;
#line 471 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_ResetParseDebugging)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::ResetParseDebugging()");
    {
#line 398 "backcalls.xs"
	ct_yydebug = 0;
#line 484 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYPushStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYPushStackState()");
    {
#line 406 "backcalls.xs"
	if (!fShouldParse) goto done;
	PushStackState();
	done:
#line 499 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYPopAndRestoreStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYPopAndRestoreStackState()");
    {
#line 415 "backcalls.xs"
	if (!fShouldParse) goto done;
	PopAndRestoreStackState();
	done:
#line 514 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYPopAndDiscardStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYPopAndDiscardStackState()");
    {
#line 424 "backcalls.xs"
	if (!fShouldParse) goto done;
	PopAndDiscardStackState();
	done:
#line 529 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYSwapStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYSwapStackState()");
    {
#line 434 "backcalls.xs"
	if (!fShouldParse) goto done;
	SwapStackState();
	done:
#line 544 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYPushDupTopStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYPushDupTopStackState()");
    {
#line 444 "backcalls.xs"
	if (!fShouldParse) goto done;
	PushDupTopStackState();
	done:
#line 559 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYFCompareTopStackState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYFCompareTopStackState()");
    {
	bool	RETVAL;
#line 454 "backcalls.xs"
        RETVAL = TRUE;
	if (!fShouldParse) goto done;
	RETVAL = FCompareTopStackState();
	done:
#line 576 "backcalls.c"
	ST(0) = boolSV(RETVAL);
	if (SvREFCNT(ST(0))) sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_pcp3_YYGetState)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYGetState()");
    {
#line 466 "backcalls.xs"
	extern int yystate;
#line 591 "backcalls.c"
	bool	RETVAL;
#line 468 "backcalls.xs"
        RETVAL = 0;
	if (!fShouldParse) goto done;
        RETVAL = yystate;
	done:
#line 598 "backcalls.c"
	ST(0) = boolSV(RETVAL);
	if (SvREFCNT(ST(0))) sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_pcp3_YYGetNode)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: pcp3::YYGetNode()");
    {
#line 480 "backcalls.xs"
	extern int yystate;
        extern tree_union ct_yylval;
#line 614 "backcalls.c"
	unsigned int	RETVAL;
#line 483 "backcalls.xs"
        RETVAL = 0;
	if (!fShouldParse) goto done;
        RETVAL = (unsigned int) ct_yylval.node;
	done:
#line 621 "backcalls.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_pcp3_YYSetState)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: pcp3::YYSetState(state_num)");
    {
	int	state_num = (int)SvIV(ST(0));
#line 497 "backcalls.xs"
	extern int yystate;
        extern tree_union ct_yylval;
#line 638 "backcalls.c"
#line 500 "backcalls.xs"
	if (fShouldParse) {
          yystate = state_num;
          ct_yylval.node = 0;
        }
#line 644 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_YYSetNode)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: pcp3::YYSetNode(node)");
    {
	unsigned int	node = (unsigned int)SvIV(ST(0));
#line 511 "backcalls.xs"
	extern int yystate;
        extern tree_union ct_yylval;
#line 659 "backcalls.c"
#line 514 "backcalls.xs"
	if (fShouldParse) {
          ct_yylval.node = node;
        }
#line 664 "backcalls.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_pcp3_FLookupSymbol)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: pcp3::FLookupSymbol(szSymbol)");
    {
	char *	szSymbol = (char *)SvPV(ST(0),na);
#line 526 "backcalls.xs"
	str_t *pstr;
	symentry_t *se;
#line 679 "backcalls.c"
	bool	RETVAL;
#line 529 "backcalls.xs"
	RETVAL = FALSE;
	if (!fShouldParse) goto done; 
	pstr = nmelook(szSymbol,strlen(szSymbol));
	if (!ParseStack || !ParseStack->contxt) {
	   RETVAL = FALSE;
	} else {
	  se = symtab_lookup(ParseStack->contxt->syms,
			     pstr);
	  RETVAL = (se != NULL);
	}
	done:
#line 693 "backcalls.c"
	ST(0) = boolSV(RETVAL);
	if (SvREFCNT(ST(0))) sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_pcp3_FLookupSymbolAt)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: pcp3::FLookupSymbolAt(szSymbol,level)");
    {
	char *	szSymbol = (char *)SvPV(ST(0),na);
	int	level = (int)SvIV(ST(1));
#line 552 "backcalls.xs"
	str_t *pstr;
	symentry_t *se;
#line 711 "backcalls.c"
	bool	RETVAL;
#line 555 "backcalls.xs"
	RETVAL = FALSE;
	if (!fShouldParse) goto done; 
	pstr = nmelook(szSymbol,strlen(szSymbol));
	if (!ParseStack || !ParseStack->contxt) {
	   RETVAL = FALSE;
	} else {
	  se = symtab_lookup_at(ParseStack->contxt->syms,
                                pstr,level);
	  RETVAL = (se != NULL);
	}
	done:
#line 725 "backcalls.c"
	ST(0) = boolSV(RETVAL);
	if (SvREFCNT(ST(0))) sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_backcalls)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("pcp3::SzToken", XS_pcp3_SzToken, file);
        newXS("pcp3::SumCchExpansionOffset", XS_pcp3_SumCchExpansionOffset, file);
        newXS("pcp3::CbuffersBack", XS_pcp3_CbuffersBack, file);
        newXS("pcp3::MacroExpansionHistory", XS_pcp3_MacroExpansionHistory, file);
        newXS("pcp3::ArgOf", XS_pcp3_ArgOf, file);
        newXS("pcp3::CchOffset", XS_pcp3_CchOffset, file);
        newXS("pcp3::InFname", XS_pcp3_InFname, file);
        newXS("pcp3::Fname", XS_pcp3_Fname, file);
        newXS("pcp3::FnameNominal", XS_pcp3_FnameNominal, file);
        newXS("pcp3::ExpansionLookup", XS_pcp3_ExpansionLookup, file);
        newXS("pcp3::CchOutput", XS_pcp3_CchOutput, file);
        newXS("pcp3::CchCppRead", XS_pcp3_CchCppRead, file);
        newXS("pcp3::FExpandingMacros", XS_pcp3_FExpandingMacros, file);
        newXS("pcp3::ParseStateStack", XS_pcp3_ParseStateStack, file);
        newXS("pcp3::SetParseStateStack", XS_pcp3_SetParseStateStack, file);
        newXS("pcp3::PushBuffer", XS_pcp3_PushBuffer, file);
        newXS("pcp3::EnterScope", XS_pcp3_EnterScope, file);
        newXS("pcp3::ExitScope", XS_pcp3_ExitScope, file);
        newXS("pcp3::PushHashTab", XS_pcp3_PushHashTab, file);
        newXS("pcp3::PopHashTab", XS_pcp3_PopHashTab, file);
        newXS("pcp3::SetParseDebugging", XS_pcp3_SetParseDebugging, file);
        newXS("pcp3::ResetParseDebugging", XS_pcp3_ResetParseDebugging, file);
        newXS("pcp3::YYPushStackState", XS_pcp3_YYPushStackState, file);
        newXS("pcp3::YYPopAndRestoreStackState", XS_pcp3_YYPopAndRestoreStackState, file);
        newXS("pcp3::YYPopAndDiscardStackState", XS_pcp3_YYPopAndDiscardStackState, file);
        newXS("pcp3::YYSwapStackState", XS_pcp3_YYSwapStackState, file);
        newXS("pcp3::YYPushDupTopStackState", XS_pcp3_YYPushDupTopStackState, file);
        newXS("pcp3::YYFCompareTopStackState", XS_pcp3_YYFCompareTopStackState, file);
        newXS("pcp3::YYGetState", XS_pcp3_YYGetState, file);
        newXS("pcp3::YYGetNode", XS_pcp3_YYGetNode, file);
        newXS("pcp3::YYSetState", XS_pcp3_YYSetState, file);
        newXS("pcp3::YYSetNode", XS_pcp3_YYSetNode, file);
        newXS("pcp3::FLookupSymbol", XS_pcp3_FLookupSymbol, file);
        newXS("pcp3::FLookupSymbolAt", XS_pcp3_FLookupSymbolAt, file);
    ST(0) = &sv_yes;
    XSRETURN(1);
}
