//$Id$
// This file is automatically generated by make --- DO NOT EDIT!
char *hook_names[] = {
"DO_DEFINE",
"HANDLE_DIRECTIVE",
"STARTUP",
"CREATE_PREDEF",
"CREATE_DEF",
"CPP_ERROR",
"CPP_WARN",
"CPP_PEDWARN",
};

