//$Id$
// This file is automatically generated by make --- DO NOT EDIT!
char *hook_names[] = {
"STARTUP",
"HANDLE_DIRECTIVE",
"DO_DEFINE",
"DO_UNDEF",
"CREATE_PREDEF",
"CREATE_DEF",
"DELETE_DEF",
"SPECIAL_SYMBOL",
"EXPAND_MACRO",
"COMMENT",
"STRING_CONSTANT",
"CPP_ERROR",
"CPP_WARN",
"CPP_PEDWARN",
};

