/*
 * This file was generated automatically by xsubpp version 1.9402 from the 
 * contents of cpp.xs. Do not edit this file, edit cpp.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "cpp.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif


XS(XS_cpp_hello)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::hello()");
    {
#line 18 "cpp.xs"
#line 18 "cpp.xs"
#line 19 "cpp.xs"
	fprintf(stdout,"Hello world!\n");
#line 19 "cpp.xs"
#line 19 "cpp.xs"
#line 19 "cpp.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_cpp_print_token_kind)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: cpp::print_token_kind(i)");
    {
	int	i = (int)SvIV(ST(0));
#line 24 "cpp.xs"
#line 24 "cpp.xs"
#line 25 "cpp.xs"
	print_token_kind((enum cpp_token) i);
#line 25 "cpp.xs"
#line 25 "cpp.xs"
#line 25 "cpp.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_cpp_fname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::fname()");
    {
#line 29 "cpp.xs"
	char *	RETVAL;
#line 29 "cpp.xs"
#line 30 "cpp.xs"
	RETVAL = parse_in.buffer->fname;
#line 32 "cpp.xs"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
#line 32 "cpp.xs"
#line 32 "cpp.xs"
    }
    XSRETURN(1);
}

XS(XS_cpp_nominal_fname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::nominal_fname()");
    {
#line 36 "cpp.xs"
	char *	RETVAL;
#line 36 "cpp.xs"
#line 37 "cpp.xs"
	RETVAL = parse_in.buffer->nominal_fname;
#line 39 "cpp.xs"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
#line 39 "cpp.xs"
#line 39 "cpp.xs"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_cpp)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("cpp::hello", XS_cpp_hello, file);
        newXS("cpp::print_token_kind", XS_cpp_print_token_kind, file);
        newXS("cpp::fname", XS_cpp_fname, file);
        newXS("cpp::nominal_fname", XS_cpp_nominal_fname, file);
    ST(0) = &sv_yes;
    XSRETURN(1);
}
