/*
 * This file was generated automatically by xsubpp version 1.9402 from the 
 * contents of cpp.xs. Do not edit this file, edit cpp.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "cpp.xs"
/* $Id$
 * By Greg J. Badros, Aug. 27 1997
 * 
 * These are simple functions to expose some C data structures
 * to the perl callbacks called from pcpp
 *
 * FIXGJB: Need the below information available:	
   is_system_include_file()
   system_include_depth()
 */


#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif


XS(XS_cpp_hello)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::hello()");
    {
#line 30 "cpp.xs"
#line 30 "cpp.xs"
#line 31 "cpp.xs"
	fprintf(stdout,"Hello world!\n");
#line 31 "cpp.xs"
#line 31 "cpp.xs"
#line 31 "cpp.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_cpp_print_token_kind)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: cpp::print_token_kind(i)");
    {
	int	i = (int)SvIV(ST(0));
#line 36 "cpp.xs"
#line 36 "cpp.xs"
#line 37 "cpp.xs"
	print_token_kind((enum cpp_token) i);
#line 37 "cpp.xs"
#line 37 "cpp.xs"
#line 37 "cpp.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_cpp_fname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::fname()");
    {
#line 41 "cpp.xs"
	char *	RETVAL;
#line 41 "cpp.xs"
#line 42 "cpp.xs"
	RETVAL = parse_in.buffer->fname;
#line 44 "cpp.xs"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
#line 44 "cpp.xs"
#line 44 "cpp.xs"
    }
    XSRETURN(1);
}

XS(XS_cpp_nominal_fname)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: cpp::nominal_fname()");
    {
#line 48 "cpp.xs"
	char *	RETVAL;
#line 48 "cpp.xs"
#line 49 "cpp.xs"
	RETVAL = parse_in.buffer->nominal_fname;
#line 51 "cpp.xs"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
#line 51 "cpp.xs"
#line 51 "cpp.xs"
    }
    XSRETURN(1);
}

XS(XS_cpp_lookup)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: cpp::lookup(sz)");
    {
	char *	sz = (char *)SvPV(ST(0),na);
#line 56 "cpp.xs"
	char *	RETVAL;
#line 56 "cpp.xs"
#line 57 "cpp.xs"
	HASHNODE *hp = cpp_lookup(&parse_in,sz,-1,-1);
	RETVAL = hp->value.defn->expansion;
#line 60 "cpp.xs"
	ST(0) = sv_newmortal();
	sv_setpv((SV*)ST(0), RETVAL);
#line 60 "cpp.xs"
#line 60 "cpp.xs"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_cpp)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("cpp::hello", XS_cpp_hello, file);
        newXS("cpp::print_token_kind", XS_cpp_print_token_kind, file);
        newXS("cpp::fname", XS_cpp_fname, file);
        newXS("cpp::nominal_fname", XS_cpp_nominal_fname, file);
        newXS("cpp::lookup", XS_cpp_lookup, file);
    ST(0) = &sv_yes;
    XSRETURN(1);
}
