#!/uns/bin/perl -wp
# Remove all the check_args_.* function calls, and replace with just "@_"
# (check_args was consuming 1/3rd of the running time for em_analyze)
s/^(\s*{)?\s*\bcheck_args(|_at_least|_range)\s*\(.*;/$1||""/e;
s/=\s*\bcheck_args(|_at_least|_range)\s*\(.*;/= \@_;/;

